ETSa:2:{s:7:"0reduce";i:2;s:4:"main";a:27:{s:5:"2:360";s:334:"

        	<div class="options">
				<div class="bg_b">
					<div class="bg_l">
						<div class="bg_r">
							<div class="bg_tr">
								<div class="bg_tl">

									<div class="bg_bl">
										<div class="bg_br">
											<div >
												<h1 style="width:60%; "><img src="img/ico_file.gif" width="16" height="20" alt="" />";s:8:"2048:364";a:2:{s:4:"test";a:2:{s:9:"4:367:id:";s:0:"";s:5:"2:370";s:2:">0";}s:4:"true";a:1:{s:5:"2:399";s:28:"Редактирование";}}s:8:"2048:408";a:2:{s:4:"test";a:2:{s:9:"4:411:id:";s:0:"";s:5:"2:416";s:4:" < 1";}s:4:"true";a:1:{s:5:"2:437";s:20:"Добавление";}}s:6:"2:1377";s:935:"&nbsp;пользователя</h1>
												
												<h2></h2>
												
												<div class="nav">
													

												</div>
												<span class="clear"></span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
            </div>




        	<table cellpadding="0" cellspacing="0">
            	<tr>
                	<td class="block_work">
                    	<div >
            				<div class="blue" >

                                <img class="blue_tl" src="img/blue_tl.gif" width="10" height="10" alt="" />
                                <img class="blue_tr" src="img/blue_tr.gif" width="10" height="10" alt="" />
                                <img class="blue_bl" src="img/blue_bl.gif" width="10" height="10" alt="" />
                                <img class="blue_br" src="img/blue_br.gif" width="10" height="10" alt="" />

	";s:6:"2:1796";s:461:"nt<formsname="form1"saction="admins_edit.php"smethod="post"senctype="multipart/form-data"sonsubmit="javascript:ifs(document.form1.password.values!=sdocument.form1.password2.value)s{alert('Паролиsнеsсовпадают.sВведите,sпожалуйста,sещеsраз.');returnsfalse;}selsesreturnstrue;">nt

	<table cellpadding="0" cellspacing="0" border="0">

	<input type="hidden" name="parent" value="";s:14:"4:1803:parent:";s:0:"";s:6:"2:1808";s:4:"">
	";s:16:"32:1821:adduser:";a:1:{s:6:"2:1867";s:46:"<input type="hidden" name="adduser" value="1">";}s:6:"2:2017";s:147:"


	<tr  >
		<th><label for="name">Имя:</label></th>
		<td ><input size=70 class="input" type="text" name="name" id="name" maxlength=255 value="";s:8:"512:2022";a:3:{s:6:"2:2040";s:18:"htmlspecialchars( ";s:22:"4:2055:cr[admin_name]:";s:0:"";s:6:"2:2058";s:2:" )";}s:6:"2:2575";s:511:""></td>
	</tr>
	<tr >
		<th><label for="password">Пароль:</label></th>
		<td ><input size=70 class="input" type="password" name="password" id="password" value=""></td>
	</tr>
	<tr  >
		<th><label for="password2">Подтверждение пароля:</label></th>
		<td ><input size=70 class="input" type="password" name="password2" id="password2" value=""></td>
	</tr>
	<tr  >
		<th><label for="email">E-mail:</label></th>
		<td ><input size=70 class="input" type="text" name="email" id="email" value="";s:8:"512:2580";a:3:{s:6:"2:2598";s:18:"htmlspecialchars( ";s:23:"4:2614:cr[admin_email]:";s:0:"";s:6:"2:2617";s:2:" )";}s:6:"2:2640";s:17:""></td>
	</tr>

	";s:22:"32:2659:user_is_super:";a:7:{s:6:"2:2823";s:164:"
	<tr  >
		<th><label for="super">Супер администратор:</label></th>
		<td ><input class="input" type="checkbox" name="super" id="super" value="1" ";s:15:"64:2836:super:1";a:1:{s:6:"2:2843";s:7:"checked";}s:6:"2:2850";s:1:" ";s:9:"2048:2854";a:2:{s:4:"test";a:3:{s:14:"4:2861:parent:";s:0:"";s:6:"2:2866";s:4:" == ";s:16:"4:2875:admin_id:";s:0:"";}s:4:"true";a:1:{s:6:"2:2886";s:9:" disabled";}}s:6:"2:2906";s:15:"></td>
	</tr>
	";s:21:"32:2924:enabled_cats:";a:3:{s:6:"2:3078";s:154:"
    <tr  >
		<th><label for="moder">Модератор:</label></th>
		<td ><input class="input" type="checkbox" name="is_moder" id="is_moder" value="1" ";s:22:"64:3098:cr[is_moder]:1";a:1:{s:6:"2:3105";s:7:"checked";}s:6:"2:3126";s:15:"></td>
	</tr>
	";}s:6:"2:3134";s:2:"
	";}s:6:"2:3147";s:7:"
	
    ";s:23:"128:3166:user_is_super:";a:3:{s:6:"2:3171";s:5:"
	   ";s:18:"32:3186:modermode:";a:1:{s:6:"2:3251";s:65:"
        	<input type="hidden" name="is_moder" value="1">
       ";}s:6:"2:3259";s:2:"
	";}s:6:"2:3265";s:3:"

	";s:9:"2048:3269";a:2:{s:4:"test";a:4:{s:6:"2:3270";s:1:" ";s:21:"4:3284:user_is_super:";s:0:"";s:6:"2:3289";s:4:" || ";s:17:"4:3299:modermode:";s:0:"";}s:4:"true";a:3:{s:6:"2:3306";s:5:"
    ";s:21:"32:3324:enabled_cats:";a:3:{s:6:"2:3395";s:71:"
    <tr  >
		<th><label for="moder">Доступ:</label></th>
		<td >";s:20:"4:3408:enabled_cats:";s:0:"";s:6:"2:3423";s:14:"</td>
	</tr>
	";}s:6:"2:3431";s:2:"
	";}}s:6:"2:3689";s:253:"



	</table>

<p></p>
                                <a name="bottom_page"></a>
								<table align="center" style="width:150px">
									<tr>
									<td>
                                	<div class="save" ><input type="submit"  name="add" value="";s:9:"2048:3693";a:2:{s:4:"test";a:2:{s:10:"4:3696:id:";s:0:"";s:6:"2:3701";s:4:" > 0";}s:4:"true";a:3:{s:6:"2:3703";s:1:" ";s:9:"2048:3707";a:2:{s:4:"test";a:2:{s:16:"4:3716:makecopy:";s:0:"";s:6:"2:3721";s:4:" < 1";}s:4:"true";a:1:{s:6:"2:3740";s:18:"Сохранить";}}s:6:"2:3746";s:1:" ";}}s:6:"2:3754";s:3:"   ";s:9:"2048:3758";a:2:{s:4:"test";a:2:{s:10:"4:3761:id:";s:0:"";s:6:"2:3764";s:2:"<1";}s:4:"true";a:1:{s:6:"2:3781";s:16:"Добавить";}}s:6:"2:3837";s:51:"" /></div>
									</td>


									<td>
									";s:9:"2048:3841";a:2:{s:4:"test";a:4:{s:6:"2:3842";s:1:" ";s:21:"4:3856:user_is_super:";s:0:"";s:6:"2:3861";s:4:" || ";s:17:"4:3871:modermode:";s:0:"";}s:4:"true";a:3:{s:6:"2:4037";s:164:"
                                	<div class="cancel"><input name="Submit2" type="button" value="Отмена" onclick="javascript:location.href='admins.php?parent=";s:14:"4:4044:parent:";s:0:"";s:6:"2:4080";s:35:"';return false;" /></div>
									";}}s:6:"2:4095";s:10:"
									";s:9:"2048:4099";a:2:{s:4:"test";a:4:{s:6:"2:4101";s:2:" !";s:21:"4:4115:user_is_super:";s:0:"";s:6:"2:4121";s:5:" && !";s:17:"4:4131:modermode:";s:0:"";}s:4:"true";a:1:{s:6:"2:4323";s:190:"
                                	<div class="cancel"><input name="Submit2" type="button" value="Отмена" onclick="javascript:location.href='index.php';return false;" /></div>
									";}}s:6:"2:4508";s:180:"

									</td>

									</tr>
								</table>
	</form>

		</div>
		</div>
	</td>
                    <td class="block" style="width:10%">
            		</td>
	</tr>
	</table>

";}}