ETSa:2:{s:7:"0reduce";i:2;s:4:"main";a:14:{s:4:"2:28";s:2:"

";s:5:"2:720";s:728:"n<scriptstype="text/javascript">n$s=s_jQuery;n$(document).ready(function(){nssss$('[name="dt_start"],s[name="dt_end"]').datepicker({changeMonth:strue,schangeYear:strue,syearRange:s'-10:c'});n});n</script>n


    <h1>Журнал событий</h1>
        
    <form method="get" name="formlog">
        <input type="hidden" id="page" name="page" value="0">
        <table class="logtable">
            <tr>
                <th>Логин</th>
                <th>Период</th>
                <th>IP</th>
                <th>Действие</th>
                <th></th>
            </tr>					
            <tr>
                <td><select name="user"><option value="">---</option>";s:12:"16:731:user:";a:7:{s:5:"2:746";s:15:"<option value="";s:11:"4:751:user:";s:0:"";s:5:"2:754";s:2:"" ";s:15:"32:767:checked:";a:1:{s:5:"2:775";s:8:"selected";}s:5:"2:779";s:1:">";s:11:"4:784:user:";s:0:"";s:5:"2:794";s:9:"</option>";}s:5:"2:902";s:101:"</select></td>
                <td>
                    с <input type="text" name="dt_start" value="";s:15:"4:911:dt_start:";s:0:"";s:6:"2:1001";s:89:"" class="input_date" />
                    по <input type="text" name="dt_end" value="";s:14:"4:1008:dt_end:";s:0:"";s:6:"2:1159";s:150:"" class="input_date" />
                </td>
                <td></td>							
                <td><select name="action"><option value="">---</option>";s:16:"16:1173:actions:";a:7:{s:6:"2:1188";s:15:"<option value="";s:13:"4:1194:value:";s:0:"";s:6:"2:1197";s:2:"" ";s:16:"32:1210:checked:";a:1:{s:6:"2:1218";s:8:"selected";}s:6:"2:1222";s:1:">";s:13:"4:1228:title:";s:0:"";s:6:"2:1238";s:9:"</option>";}s:6:"2:1500";s:255:"</select></td>
                <td></td>							
            </tr>
            <tr>
                <td colspan="5" class="filter-bottom"><input type="submit" class="button_large" value="Применить фильтр"></td>
            </tr>
            ";s:13:"16:1511:logs:";a:15:{s:6:"2:1549";s:38:"
            <tr>
                <td>";s:12:"4:1554:user:";s:0:"";s:6:"2:1581";s:26:"</td>
                <td>";s:12:"4:1586:dt_1:";s:0:"";s:6:"2:1613";s:26:"</td>
                <td>";s:10:"4:1616:ip:";s:0:"";s:6:"2:1664";s:47:"</td>
                <td>
                    ";s:20:"4:1677:action_title:";s:0:"";s:6:"2:1699";s:21:"
                    ";s:14:"256:1710:bid:0";a:5:{s:6:"2:1711";s:1:"[";s:11:"4:1715:bid:";s:0:"";s:6:"2:1719";s:3:"] [";s:13:"4:1725:btype:";s:0:"";s:6:"2:1727";s:1:"]";}s:6:"2:1751";s:21:"
                    ";s:13:"32:1761:link:";a:3:{s:6:"2:1770";s:9:"<a href="";s:12:"4:1775:link:";s:0:"";s:6:"2:1794";s:18:"" target="_blank">";}s:12:"4:1802:info:";s:0:"";s:13:"32:1813:link:";a:1:{s:6:"2:1817";s:4:"</a>";}s:6:"2:1899";s:79:"
                </td>
                <td></td>
            </tr>
            ";}s:6:"2:1954";s:48:"						
        </table>

        <br />
        ";s:14:"32:1965:pages:";a:3:{s:6:"2:1992";s:27:"Страницы: 
        ";s:14:"16:2004:pages:";a:5:{s:6:"2:2017";s:13:"
            ";s:17:"128:2030:current:";a:5:{s:6:"2:2090";s:60:"<a href="#" onclick="document.getElementById('page').value='";s:11:"4:2094:num:";s:0:"";s:6:"2:2125";s:30:"';document.formlog.submit();">";s:13:"4:2131:title:";s:0:"";s:6:"2:2136";s:4:"</a>";}s:6:"2:2152";s:13:"
            ";s:16:"32:2165:current:";a:3:{s:6:"2:2168";s:3:"<b>";s:13:"4:2174:title:";s:0:"";s:6:"2:2179";s:4:"</b>";}s:6:"2:2191";s:9:"
        ";}s:6:"2:2207";s:9:"
        ";}s:6:"2:2229";s:16:"

    </form>


";}}