ETSa:2:{s:7:"0reduce";i:2;s:4:"main";a:18:{s:5:"2:361";s:335:"


        	<div class="options">
				<div class="bg_b">
					<div class="bg_l">
						<div class="bg_r">
							<div class="bg_tr">
								<div class="bg_tl">

									<div class="bg_bl">
										<div class="bg_br">
											<div >
												<h1 style="width:60%; "><img src="img/ico_file.gif" width="16" height="20" alt="" />";s:8:"2048:365";a:2:{s:4:"test";a:2:{s:9:"4:368:id:";s:0:"";s:5:"2:371";s:2:">0";}s:4:"true";a:1:{s:5:"2:400";s:28:"Редактирование";}}s:8:"2048:409";a:2:{s:4:"test";a:2:{s:9:"4:412:id:";s:0:"";s:5:"2:417";s:4:" < 1";}s:4:"true";a:1:{s:5:"2:438";s:20:"Добавление";}}s:6:"2:1557";s:1114:"&nbsp;типа&nbsp;данных</h1>
												
												<h2></h2>
												
												<div class="nav">
													

												</div>
												<span class="clear"></span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
            </div>


        	<table cellpadding="0" cellspacing="0">
            	<tr>
                	<td class="block_work">
                    	<div >
            				<div class="blue">

                                <img class="blue_tl" src="img/blue_tl.gif" width="10" height="10" alt="" />
                                <img class="blue_tr" src="img/blue_tr.gif" width="10" height="10" alt="" />
                                <img class="blue_bl" src="img/blue_bl.gif" width="10" height="10" alt="" />
                                <img class="blue_br" src="img/blue_br.gif" width="10" height="10" alt="" />

	<table cellpadding="0" cellspacing="0" border="0">			

	<form action="s_datatempl_edit.php" method="post" enctype="multipart/form-data">
	<input type="hidden" name="parent" value="";s:14:"4:1564:parent:";s:0:"";s:6:"2:1613";s:48:"">
	<input type="hidden" name="makecopy" value="";s:16:"4:1622:makecopy:";s:0:"";s:6:"2:1779";s:156:"">
	<tr >
		<th><label for="name">Название:</label></th>
		<td ><input size=70 class="input" type="text" name="name" id="name" maxlength=255 value="";s:8:"512:1784";a:3:{s:6:"2:1801";s:17:"htmlspecialchars(";s:16:"4:1810:cr[name]:";s:0:"";s:6:"2:1812";s:1:")";}s:6:"2:1961";s:143:""></td>
	</tr>
	<tr >
		<th><label for="key">Ключ:</label></th>
		<td ><input size=70 class="input" type="text" name="key" id="key" value="";s:8:"512:1966";a:3:{s:6:"2:1983";s:17:"htmlspecialchars(";s:15:"4:1991:cr[key]:";s:0:"";s:6:"2:1993";s:1:")";}s:6:"2:2258";s:259:""></td>
	</tr>


	</table>

	                                <a name="bottom_page"></a>
								<table align="center" style="width:150px">
									<tr>
									<td>
                                	<div class="save" ><input type="submit"  name="add" value="";s:9:"2048:2262";a:2:{s:4:"test";a:2:{s:10:"4:2265:id:";s:0:"";s:6:"2:2268";s:2:">0";}s:4:"true";a:1:{s:6:"2:2287";s:18:"Сохранить";}}s:6:"2:2293";s:1:" ";s:9:"2048:2297";a:2:{s:4:"test";a:2:{s:10:"4:2300:id:";s:0:"";s:6:"2:2305";s:4:" < 1";}s:4:"true";a:1:{s:6:"2:2322";s:16:"Добавить";}}s:6:"2:2538";s:211:"" /></div>
									</td>



									<td>
                                	<div class="cancel"><input name="Submit2" type="button" value="Отмена" onclick="javascript:location.href='s_datatempl.php?parent=";s:14:"4:2545:parent:";s:0:"";s:6:"2:2767";s:221:"';return false;" /></div>
									</td>

									</tr>
								</table>
	</form>
					</div></td>

                   <td class="block" style="width:10%">
            		</td>
                </tr>
            </table>

";}}