ETSa:2:{s:7:"0reduce";i:2;s:4:"main";a:19:{s:6:"2:1598";s:1572:"
<div class="options">
    <div class="bg_b">
        <div class="bg_l">
            <div class="bg_r">
                <div class="bg_tr">
                    <div class="bg_tl">
                        <div class="bg_bl">
                            <div class="bg_br">
                                <div>
                                    <h1 style="width:60%; "><img src="http://cms.smhost.ru/admin/img/ico_file.gif"
                                                                 width="16" height="20" alt=""/>Список заявок</h1>
                                    <h2>&nbsp;</h2>
                                    <div class="nav">
                                    </div>
                                    <span class="clear"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<table style="width:400px" cellpadding="0" cellspacing="0"	>
    <tr>
        <td >
            <div class="new_block"><a href="#" onclick="location.assign('support.php?action=new');" title="Новый блок">Новая заявка</a></div>
        </td>
    </tr>
</table>
<table class="in_cont" cellpadding="0" cellspacing="0" style="width:100%">
    <tr>
        <td align="center" style="width:80%" valign="top">

            <div class="with_page">
                <div class="type-list">
                    <div class="title">Статус заявок</div>
                    <a class="";s:19:"64:1615:status:open";a:1:{s:6:"2:1621";s:6:"active";}s:6:"2:1677";s:53:"" href="?status=open"><span>Открытые</span> (";s:15:"16:1693.1:count";a:1:{s:13:"32:1693:open:";a:1:{s:12:"4:1698:open:";s:0:"";}}s:20:"1048576:1718.1:count";a:1:{s:14:"128:1718:open:";a:1:{s:6:"2:1719";s:1:"0";}}s:6:"2:1758";s:36:")</a>
                    <a class="";s:21:"64:1777:status:closed";a:1:{s:6:"2:1783";s:6:"active";}s:6:"2:1841";s:55:"" href="?status=closed"><span>Закрытые</span> (";s:15:"16:1859.1:count";a:1:{s:15:"32:1859:closed:";a:1:{s:14:"4:1866:closed:";s:0:"";}}s:20:"1048576:1888.1:count";a:1:{s:16:"128:1888:closed:";a:1:{s:6:"2:1889";s:1:"0";}}s:6:"2:1938";s:46:")</a>
                </div>

                ";s:14:"32:1949:error:";a:1:{s:6:"2:2007";s:58:"<h4 style="color:red">Произошла ошибка</h4>";}s:6:"2:2027";s:17:"
                ";s:16:"32:2040:success:";a:1:{s:6:"2:2111";s:71:"<h4 style="color:green">Заявка успешно создана</h4>";}s:6:"2:2132";s:18:"

                ";s:15:"32:2144:result:";a:3:{s:6:"2:3009";s:865:"<table style="width:100%;" border="0" cellspacing="0" cellpadding="1" id="divtable">
                    <tbody>
                    <tr>
                        <th class="left" style="width:1% !important;"></th>
                        <th style="background: #e7e7e7;">№</th>
                        <th nowrap="nowrap" style="background: #e7e7e7; ">Тема</th>
                        <th nowrap="nowrap" style="background: #e7e7e7; ">Имя</th>
                        <th nowrap="nowrap" style="background: #e7e7e7; ">E-mail</th>
                        <th nowrap="nowrap" style="background: #e7e7e7; ">Время создания</th>
                        <th nowrap="nowrap" style="background: #e7e7e7; ">Время последнего ответа</th>
                        <th class="right"></th>
                    </tr>
                    ";s:15:"16:3022:result:";a:19:{s:6:"2:3051";s:29:"
                    <tr id="";s:10:"4:3054:id:";s:0:"";s:6:"2:3357";s:302:"" style="cursor:pointer">
                        <td style="width:1% !important; padding-right:0px; padding-left:7px;">
                            <img src="img/ico_file.gif" width="16" height="20" alt="">
                        </td>
                        <td><a href="support.php?action=view&id=";s:17:"4:3367:ticket_id:";s:0:"";s:6:"2:3370";s:2:"">";s:16:"4:3379:ticketID:";s:0:"";s:6:"2:3470";s:90:"</a></td>
                        <td nowrap="nowrap"><a href="support.php?action=view&id=";s:17:"4:3480:ticket_id:";s:0:"";s:6:"2:3483";s:2:"">";s:15:"4:3491:subject:";s:0:"";s:6:"2:3546";s:54:"</a></td>
                        <td nowrap="nowrap">";s:12:"4:3551:name:";s:0:"";s:6:"2:3602";s:50:"</td>
                        <td nowrap="nowrap">";s:13:"4:3608:email:";s:0:"";s:6:"2:3659";s:50:"</td>
                        <td nowrap="nowrap">";s:15:"4:3667:created:";s:0:"";s:6:"2:3718";s:50:"</td>
                        <td nowrap="nowrap">";s:20:"4:3731:lastresponse:";s:0:"";s:6:"2:3797";s:65:"</td>
                        <td></td>
                    </tr>";}s:6:"2:3854";s:54:"
                    </tbody>
                </table>";}s:6:"2:3874";s:17:"
                ";s:16:"128:3886:result:";a:1:{s:6:"2:3961";s:75:"
                <p>Список заявок пуст</p>
                ";}s:6:"2:4017";s:53:"
            </div>
        </td>
    </tr>
</table>
";}}