ETSa:2:{s:7:"0reduce";i:2;s:4:"main";a:58:{s:5:"2:361";s:335:"


        	<div class="options">
				<div class="bg_b">
					<div class="bg_l">
						<div class="bg_r">
							<div class="bg_tr">
								<div class="bg_tl">

									<div class="bg_bl">
										<div class="bg_br">
											<div >
												<h1 style="width:60%; "><img src="img/ico_file.gif" width="16" height="20" alt="" />";s:8:"2048:365";a:2:{s:4:"test";a:2:{s:9:"4:368:id:";s:0:"";s:5:"2:371";s:2:">0";}s:4:"true";a:1:{s:5:"2:400";s:28:"Редактирование";}}s:8:"2048:409";a:2:{s:4:"test";a:2:{s:9:"4:412:id:";s:0:"";s:5:"2:417";s:4:" < 1";}s:4:"true";a:1:{s:5:"2:438";s:20:"Добавление";}}s:6:"2:1599";s:1156:"&nbsp;шаблона&nbsp;папок</h1>
												
												<h2></h2>
												
												<div class="nav">
													

												</div>
												<span class="clear"></span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
            </div>



        	

        	<table cellpadding="0" cellspacing="0">
            	<tr>
                	<td class="block_work">
                    	<div >
            				<div class="blue" >

                                <img class="blue_tl" src="img/blue_tl.gif" width="10" height="10" alt="" />
                                <img class="blue_tr" src="img/blue_tr.gif" width="10" height="10" alt="" />
                                <img class="blue_bl" src="img/blue_bl.gif" width="10" height="10" alt="" />
                                <img class="blue_br" src="img/blue_br.gif" width="10" height="10" alt="" />



	<table cellpadding="0" cellspacing="0" border="0">


	<form action="s_cattempl_edit.php#bottom_page" method="post" enctype="multipart/form-data" name="form1">
	<input type="hidden" name="nfields" value="";s:15:"4:1607:nfields:";s:0:"";s:6:"2:1654";s:46:"">
	<input type="hidden" name="parent" value="";s:14:"4:1661:parent:";s:0:"";s:6:"2:1710";s:48:"">
	<input type="hidden" name="makecopy" value="";s:16:"4:1719:makecopy:";s:0:"";s:6:"2:1767";s:47:"">
	<input type="hidden" name="oldbkey" value="";s:11:"4:1771:key:";s:0:"";s:6:"2:2029";s:257:"">
	<input type="hidden" name="removefield" value="0">

	<input type="hidden" name="add2" value="0">



	<tr >
		<th><label for="name">Название:</label></th>
		<td ><input class="input" type="text" size=70 name="name" id="name" maxlength=255 value="";s:8:"512:2034";a:3:{s:6:"2:2051";s:17:"htmlspecialchars(";s:12:"4:2056:name:";s:0:"";s:6:"2:2058";s:1:")";}s:6:"2:2208";s:144:""></td>
	</tr>
	<tr  >
		<th><label for="key">Ключ:</label></th>
		<td ><input class="input" type="text" size=70 name="key" id="key" value="";s:8:"512:2213";a:3:{s:6:"2:2230";s:17:"htmlspecialchars(";s:11:"4:2234:key:";s:0:"";s:6:"2:2236";s:1:")";}s:6:"2:2402";s:160:""></td>
	</tr>
	<tr  >
		<th><label for="alias">Псевдоним:</label></th>
		<td ><input class="input" type="text" size=70 name="alias" id="alias" value="";s:8:"512:2407";a:3:{s:6:"2:2424";s:17:"htmlspecialchars(";s:13:"4:2430:alias:";s:0:"";s:6:"2:2432";s:1:")";}s:6:"2:2617";s:179:""></td>
	</tr>
	<tr  >
		<th><label for="abc">Постраничное разбиение:</label></th>
		<td ><input class="input" type="text" size=70 name="abc" id="abc" value="";s:8:"512:2622";a:3:{s:6:"2:2639";s:17:"htmlspecialchars(";s:11:"4:2643:abc:";s:0:"";s:6:"2:2645";s:1:")";}s:6:"2:3061";s:410:""><br>
		укажите количество элементов на странице и, <br>если требуется, через запятую укажите количество видимых страниц.</td>
	</tr>
	<tr  >
		<th><label for="filterfield">Ключ поля для поиска:</label></th>
		<td ><input class="input" type="text" size=70 name="filterfield" id="filterfield" value="";s:8:"512:3066";a:3:{s:6:"2:3083";s:17:"htmlspecialchars(";s:19:"4:3095:filterfield:";s:0:"";s:6:"2:3097";s:1:")";}s:6:"2:3293";s:190:""></td>
	</tr>
	<tr >
		<th><label for="sortfield">Сортировка по ключу:</label></th>
		<td ><input class="input" type="text" size=70 name="sortfield" id="sortfield"  value="";s:8:"512:3298";a:3:{s:6:"2:3315";s:17:"htmlspecialchars(";s:17:"4:3325:sortfield:";s:0:"";s:6:"2:3327";s:1:")";}s:6:"2:3509";s:176:""></td>
	</tr>

	<tr  >
		<th><label for="candel">Право на удаление:</label></th>
		<td ><input class="input" type="checkbox" name="candel" id="candel" value="1"";s:9:"2048:3513";a:2:{s:4:"test";a:2:{s:14:"4:3520:candel:";s:0:"";s:6:"2:3525";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:3534";s:8:" checked";}}s:6:"2:3739";s:200:"></td>
	</tr>
	<tr >
		<th><label for="caneditname">Право на переименование:</label></th>
		<td ><input class="input" type="checkbox" name="caneditname" id="caneditname" value="1"";s:9:"2048:3743";a:2:{s:4:"test";a:2:{s:19:"4:3755:caneditname:";s:0:"";s:6:"2:3760";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:3769";s:8:" checked";}}s:6:"2:3963";s:189:"></td>
	</tr>
	<tr  >
		<th><label for="canedit">Право на редактирование:</label></td>
		<td ><input class="input" type="checkbox" name="canedit" id="canedit" value="1"";s:9:"2048:3967";a:2:{s:4:"test";a:2:{s:15:"4:3975:canedit:";s:0:"";s:6:"2:3980";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:3989";s:8:" checked";}}s:6:"2:4194";s:200:"></td>
	</tr>
	<tr  >
		<th><label for="canaddcat">Право на создание подпапок:</label></th>
		<td ><input class="input" type="checkbox" name="canaddcat" id="canaddcat" value="1"";s:9:"2048:4198";a:2:{s:4:"test";a:2:{s:17:"4:4208:canaddcat:";s:0:"";s:6:"2:4213";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:4222";s:8:" checked";}}s:6:"2:4420";s:193:"></td>
	</tr>
	<tr  >
		<th><label for="canaddbl">Право на создание блоков:</label></th>
		<td ><input class="input" type="checkbox" name="canaddbl" id="canaddbl" value="1"";s:9:"2048:4424";a:2:{s:4:"test";a:2:{s:16:"4:4433:canaddbl:";s:0:"";s:6:"2:4438";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:4447";s:8:" checked";}}s:6:"2:4644";s:192:"></td>
	</tr>
	<tr  >
		<th><label for="canmoveto">Право на перенос папки:</label></th>
		<td ><input class="input" type="checkbox" name="canmoveto" id="canmoveto" value="1"";s:9:"2048:4648";a:2:{s:4:"test";a:2:{s:17:"4:4658:canmoveto:";s:0:"";s:6:"2:4663";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:4672";s:8:" checked";}}s:6:"2:4877";s:200:"></td>
	</tr>
	<tr  >
		<th><label for="cancopyto">Право на копирование папки:</label></th>
		<td ><input class="input" type="checkbox" name="cancopyto" id="cancopyto" value="1"";s:9:"2048:4881";a:2:{s:4:"test";a:2:{s:17:"4:4891:cancopyto:";s:0:"";s:6:"2:4896";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:4905";s:8:" checked";}}s:6:"2:5113";s:203:"></td>
	</tr>
	<tr  >
		<th><label for="canmovefrom">Право на перенос из папки:</label></td>
		<td ><input class="input" type="checkbox" name="canmovefrom" id="canmovefrom" value="1"";s:9:"2048:5117";a:2:{s:4:"test";a:2:{s:19:"4:5129:canmovefrom:";s:0:"";s:6:"2:5134";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:5143";s:8:" checked";}}s:6:"2:5359";s:211:"></td>
	</tr>
	<tr  >
		<th><label for="cancopyfrom">Право на копирование из папки:</label></th>
		<td ><input class="input" type="checkbox" name="cancopyfrom" id="cancopyfrom" value="1"";s:9:"2048:5363";a:2:{s:4:"test";a:2:{s:19:"4:5375:cancopyfrom:";s:0:"";s:6:"2:5380";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:5389";s:8:" checked";}}s:6:"2:5580";s:186:"></td>
	</tr>
	<tr  >
		<th><label for="canhide">Право на скрытие/показ:</label></th>
		<td ><input class="input" type="checkbox" name="canhide" id="canhide" value="1"";s:9:"2048:5584";a:2:{s:4:"test";a:2:{s:15:"4:5592:canhide:";s:0:"";s:6:"2:5597";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:5606";s:8:" checked";}}s:6:"2:5791";s:180:"></td>
	</tr>
	<tr  >
		<th><label for="hidestr">Скрывать структуру:</label></th>
		<td ><input class="input" type="checkbox" name="hidestr" id="hidestr" value="1"";s:9:"2048:5795";a:2:{s:4:"test";a:2:{s:15:"4:5803:hidestr:";s:0:"";s:6:"2:5808";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:5817";s:8:" checked";}}s:6:"2:6422";s:600:"></td>
	</tr>

	<script>
		function selectSort(name, dir)
		{
			var $el = _jQuery('[name="' + name + '"]');
			var $opt = $el.children('option:selected');
			switch (dir) {
				case 'up':
					var $prev = $opt.prev();
					if ($prev.length)
						$opt.detach().insertBefore($prev);
					break;
				case 'down':
					var $next = $opt.next();
					if ($next.length)
						$opt.detach().insertAfter($next);
					break;
			}
		}
	</script>

	<tr  >
		<th>Возможные шаблоны блоков:</th>
		<td >
			<select class="input" name="blocktypes[]" multiple size="10" style="width:50%">
				";s:15:"16:6435:tblock:";a:9:{s:6:"2:6456";s:21:"
					<option value="";s:8:"512:6461";a:3:{s:6:"2:6478";s:17:"htmlspecialchars(";s:16:"4:6487:row[key]:";s:0:"";s:6:"2:6489";s:1:")";}s:6:"2:6497";s:2:"" ";s:16:"4:6506:selected:";s:0:"";s:6:"2:6508";s:1:">";s:8:"512:6513";a:3:{s:6:"2:6524";s:11:"strip_tags(";s:17:"4:6534:row[name]:";s:0:"";s:6:"2:6536";s:1:")";}s:6:"2:6544";s:2:" (";s:8:"512:6549";a:3:{s:6:"2:6566";s:17:"htmlspecialchars(";s:16:"4:6575:row[key]:";s:0:"";s:6:"2:6577";s:1:")";}s:6:"2:6598";s:15:")</option>
				";}s:6:"2:6963";s:358:"
			</select>
			<br>
			<button type="button" onclick="selectSort('blocktypes[]', 'up')">UP</button> <button type="button" onclick="selectSort('blocktypes[]', 'down')">DOWN</button>
		</td>
	</tr>	

	<tr  >
		<th>Возможные шаблоны папок:</th>
		<td >
			<select class="input" name="cattypes[]" multiple size="15" style="width:50%">
				";s:14:"16:6975:tcats:";a:9:{s:6:"2:6996";s:21:"
					<option value="";s:8:"512:7001";a:3:{s:6:"2:7018";s:17:"htmlspecialchars(";s:16:"4:7027:row[key]:";s:0:"";s:6:"2:7029";s:1:")";}s:6:"2:7037";s:2:"" ";s:16:"4:7046:selected:";s:0:"";s:6:"2:7048";s:1:">";s:8:"512:7053";a:3:{s:6:"2:7064";s:11:"strip_tags(";s:17:"4:7074:row[name]:";s:0:"";s:6:"2:7076";s:1:")";}s:6:"2:7084";s:2:" (";s:8:"512:7089";a:3:{s:6:"2:7106";s:17:"htmlspecialchars(";s:16:"4:7115:row[key]:";s:0:"";s:6:"2:7117";s:1:")";}s:6:"2:7138";s:15:")</option>
				";}s:6:"2:7342";s:197:"
			</select>
			<br>
			<button type="button" onclick="selectSort('cattypes[]', 'up')">UP</button> <button type="button" onclick="selectSort('cattypes[]', 'down')">DOWN</button>
		</td>
	</tr>


	";s:9:"2048:7346";a:2:{s:4:"test";a:2:{s:21:"4:7360:num_datatypes:";s:0:"";s:6:"2:7364";s:3:" >0";}s:4:"true";a:3:{s:6:"2:7368";s:3:"
		";s:9:"2048:7372";a:2:{s:4:"test";a:2:{s:15:"4:7380:nfields:";s:0:"";s:6:"2:7385";s:4:" > 0";}s:4:"true";a:3:{s:6:"2:8012";s:626:"

		<tr >
			<td colspan=2 >
				&nbsp;
			</td>
		</tr>
		<tr >
			<td colspan=2 bgcolor="#EEEEEE">
				<p></p>
				
				<table cellspacing=0 cellpadding=3 border=0 width=100%>
					<tr >
						<td width=1%><b>Поля:</b></td>
						<td width=10%>имя</td>
						<td width=10%>ключ</td>
						<td width=20%>тип данных</td>
						<td width=10%>по умолчанию</td>
						<td width=25%>служебная информация</td>
						<td width=10%>аттрибуты</td>
						<td width=1%>сорт.</td>
						<td width=1%>неред.</td>


						<td width=10%>&nbsp;</td>
					</tr>

					

				";s:15:"16:8025:nfield:";a:47:{s:6:"2:8092";s:67:"

			<tr>
				<td align="left"  valign=center nowrap><b>Поле N ";s:9:"4:8094:i:";s:0:"";s:6:"2:8187";s:92:":&nbsp;</b></td>

				<td ><input style="width:100%" class="input" type="text" name="nfieldn";s:9:"4:8189:i:";s:0:"";s:6:"2:8207";s:17:"" size=20 value="";s:8:"512:8212";a:3:{s:6:"2:8229";s:17:"htmlspecialchars(";s:15:"4:8237:nfieldn:";s:0:"";s:6:"2:8239";s:1:")";}s:6:"2:8327";s:82:""></td>

				<td><input style="width:100%" class="input" type="text" name="nfieldk";s:9:"4:8329:i:";s:0:"";s:6:"2:8347";s:17:"" size=20 value="";s:8:"512:8352";a:3:{s:6:"2:8369";s:17:"htmlspecialchars(";s:15:"4:8377:nfieldk:";s:0:"";s:6:"2:8379";s:1:")";}s:6:"2:8430";s:45:"">
				<input type="hidden" name="old_name_f[";s:8:"512:8435";a:3:{s:6:"2:8452";s:17:"htmlspecialchars(";s:15:"4:8460:nfieldk:";s:0:"";s:6:"2:8462";s:1:")";}s:6:"2:8478";s:10:"]" value="";s:8:"512:8483";a:3:{s:6:"2:8500";s:17:"htmlspecialchars(";s:15:"4:8508:nfieldk:";s:0:"";s:6:"2:8510";s:1:")";}s:6:"2:8561";s:45:"">
				<input type="hidden" name="old_nfieldk";s:9:"4:8563:i:";s:0:"";s:6:"2:8573";s:9:"" value="";s:8:"512:8578";a:3:{s:6:"2:8595";s:17:"htmlspecialchars(";s:15:"4:8603:nfieldk:";s:0:"";s:6:"2:8605";s:1:")";}s:6:"2:8620";s:9:"" value="";s:8:"512:8625";a:3:{s:6:"2:8642";s:17:"htmlspecialchars(";s:15:"4:8650:nfieldk:";s:0:"";s:6:"2:8652";s:1:")";}s:6:"2:8734";s:76:"">
				</td>

				<td ><select style="width:100%" class="input" name="nfield";s:9:"4:8736:i:";s:0:"";s:6:"2:8746";s:9:"">
						";s:12:"16:8756:row:";a:9:{s:6:"2:8779";s:23:"
							<option value="";s:8:"512:8784";a:3:{s:6:"2:8801";s:17:"htmlspecialchars(";s:16:"4:8810:row[key]:";s:0:"";s:6:"2:8812";s:1:")";}s:6:"2:8820";s:2:"" ";s:16:"4:8829:selected:";s:0:"";s:6:"2:8840";s:10:">
								";s:8:"512:8845";a:3:{s:6:"2:8856";s:11:"strip_tags(";s:17:"4:8866:row[name]:";s:0:"";s:6:"2:8868";s:1:")";}s:6:"2:8876";s:2:" (";s:8:"512:8881";a:3:{s:6:"2:8898";s:17:"htmlspecialchars(";s:16:"4:8907:row[key]:";s:0:"";s:6:"2:8909";s:1:")";}s:6:"2:8940";s:25:")
							</option>
						";}s:6:"2:9043";s:96:"

					</select></td>

				<td><input style="width:100%" class="input" type="text" name="nfieldd";s:9:"4:9045:i:";s:0:"";s:6:"2:9063";s:17:"" size=35 value="";s:8:"512:9068";a:3:{s:6:"2:9085";s:17:"htmlspecialchars(";s:15:"4:9093:nfieldd:";s:0:"";s:6:"2:9095";s:1:")";}s:6:"2:9187";s:86:""></td>
				
				<td><input style="width:100%" class="input" type="text" name="nfieldc";s:9:"4:9189:i:";s:0:"";s:6:"2:9207";s:17:"" size=50 value="";s:8:"512:9212";a:3:{s:6:"2:9229";s:17:"htmlspecialchars(";s:15:"4:9237:nfieldc:";s:0:"";s:6:"2:9239";s:1:")";}s:6:"2:9331";s:86:""></td>
				
				<td><input style="width:100%" class="input" type="text" name="nfielda";s:9:"4:9333:i:";s:0:"";s:6:"2:9351";s:17:"" size=35 value="";s:8:"512:9356";a:3:{s:6:"2:9373";s:17:"htmlspecialchars(";s:15:"4:9381:nfielda:";s:0:"";s:6:"2:9383";s:1:")";}s:6:"2:9493";s:104:""></td>
				
				<td align="center"><input style="width:30px" class="input" type="text" name="nfieldsort";s:9:"4:9495:i:";s:0:"";s:6:"2:9513";s:17:"" size=35 value="";s:8:"512:9518";a:3:{s:6:"2:9535";s:17:"htmlspecialchars(";s:18:"4:9546:nfieldsort:";s:0:"";s:6:"2:9548";s:1:")";}s:6:"2:9611";s:57:""></td>
				
				<td><input type="checkbox" name="nfieldr";s:9:"4:9613:i:";s:0:"";s:6:"2:9639";s:25:"" class="input" value="1"";s:9:"2048:9643";a:2:{s:4:"test";a:2:{s:15:"4:9651:nfieldr:";s:0:"";s:6:"2:9656";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:9665";s:8:" checked";}}s:6:"2:9830";s:160:"></td>
				
				<td><input class="input" style="width:100%;height:20px" type="button" value="убрать" onClick="javascript:document.form1.removefield.value=";s:9:"4:9832:i:";s:0:"";s:6:"2:9892";s:59:";document.form1.submit();return false;"></td>
			</tr>

			";}s:6:"2:9934";s:35:"


				</table>
			</td>
		</tr>
		";}}s:6:"2:9941";s:2:"
	";}}s:7:"2:10199";s:253:"



	</table>

<p></p>
                                <a name="bottom_page"></a>
								<table align="center" style="width:300px">
									<tr>
									<td>
                                	<div class="save" ><input type="submit"  name="add" value="";s:10:"2048:10203";a:2:{s:4:"test";a:2:{s:11:"4:10206:id:";s:0:"";s:7:"2:10209";s:2:">0";}s:4:"true";a:1:{s:7:"2:10228";s:18:"Сохранить";}}s:7:"2:10234";s:1:" ";s:10:"2048:10238";a:2:{s:4:"test";a:2:{s:11:"4:10241:id:";s:0:"";s:7:"2:10246";s:4:" < 1";}s:4:"true";a:1:{s:7:"2:10263";s:16:"Добавить";}}s:7:"2:10697";s:429:"" /></div>
									</td>

									<td>
                                	<div class="save" ><input type="button"  value="Применить" onClick="document.form1.add2.value='1';  document.form1.submit(); return false;" /></div>
									</td>

									<td>
                                	<div class="cancel"><input name="Submit2" type="button" value="Отмена" onclick="javascript:location.href='s_cattempl.php?parent=";s:15:"4:10704:parent:";s:0:"";s:7:"2:11209";s:504:"';return false;" /></div>
									</td>
									<td>
									<div class="save" ><input name="Submit3" type="button" value="Добавить поле" onclick="document.form1.nfields.value++;document.form1.submit();return false;" /></div>

									</td>
									</tr>
								</table>
                              	</div>

	</form>


            			</div>
            		</td>
                    <td class="block" style="width:10%">
            		</td>
                </tr>
            </table>



";}}