ETSa:2:{s:7:"0reduce";i:2;s:4:"main";a:42:{s:5:"2:361";s:335:"


        	<div class="options">
				<div class="bg_b">
					<div class="bg_l">
						<div class="bg_r">
							<div class="bg_tr">
								<div class="bg_tl">

									<div class="bg_bl">
										<div class="bg_br">
											<div >
												<h1 style="width:60%; "><img src="img/ico_file.gif" width="16" height="20" alt="" />";s:8:"2048:365";a:2:{s:4:"test";a:2:{s:9:"4:368:id:";s:0:"";s:5:"2:371";s:2:">0";}s:4:"true";a:1:{s:5:"2:400";s:28:"Редактирование";}}s:8:"2048:409";a:2:{s:4:"test";a:2:{s:9:"4:412:id:";s:0:"";s:5:"2:417";s:4:" < 1";}s:4:"true";a:1:{s:5:"2:438";s:20:"Добавление";}}s:6:"2:1583";s:1140:"&nbsp;шаблона&nbsp;блока</h1>
												
												<h2></h2>
												
												<div class="nav">
													

												</div>
												<span class="clear"></span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
            </div>


        	<table cellpadding="0" cellspacing="0">
            	<tr>
                	<td class="block_work">
                    	<div >
            				<div class="blue">

                                <img class="blue_tl" src="img/blue_tl.gif" width="10" height="10" alt="" />
                                <img class="blue_tr" src="img/blue_tr.gif" width="10" height="10" alt="" />
                                <img class="blue_bl" src="img/blue_bl.gif" width="10" height="10" alt="" />
                                <img class="blue_br" src="img/blue_br.gif" width="10" height="10" alt="" />

	<table cellpadding="0" cellspacing="0" border="0">


	<form action="s_bltempl_edit.php#bottom_page" method="post" enctype="multipart/form-data" name="form1">
	<input type="hidden" name="nfields" value="";s:15:"4:1591:nfields:";s:0:"";s:6:"2:1638";s:46:"">
	<input type="hidden" name="parent" value="";s:14:"4:1645:parent:";s:0:"";s:6:"2:1694";s:48:"">
	<input type="hidden" name="makecopy" value="";s:16:"4:1703:makecopy:";s:0:"";s:6:"2:1751";s:47:"">
	<input type="hidden" name="oldbkey" value="";s:11:"4:1755:key:";s:0:"";s:6:"2:2012";s:256:"">
	<input type="hidden" name="removefield" value="0">

	<input type="hidden" name="add2" value="0">

	<tr  >
		<th><label for="name">Название:</label></th>
		<td ><input class="input" size=70 type="text" name="name" id="name" maxlength=255 value="";s:8:"512:2017";a:3:{s:6:"2:2034";s:17:"htmlspecialchars(";s:12:"4:2039:name:";s:0:"";s:6:"2:2041";s:1:")";}s:6:"2:2205";s:158:""></td>
	</tr>
	<tr  >
		<th><label for="key">Ключ:</label></th>
		<td ><input class="input" size=70 type="text" name="key" id="key" maxlength=255 value="";s:8:"512:2210";a:3:{s:6:"2:2227";s:17:"htmlspecialchars(";s:11:"4:2231:key:";s:0:"";s:6:"2:2233";s:1:")";}s:6:"2:2414";s:175:""></td>
	</tr>
	<tr  >
		<th><label for="candel">Право на удаление:</label></th>
		<td ><input class="input" type="checkbox" name="candel" id="candel" value="1"";s:9:"2048:2418";a:2:{s:4:"test";a:2:{s:14:"4:2425:candel:";s:0:"";s:6:"2:2430";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:2439";s:8:" checked";}}s:6:"2:2633";s:189:"></td>
	</tr>
	<tr  >
		<th><label for="canedit">Право на редактирование:</label></th>
		<td ><input class="input" type="checkbox" name="canedit" id="canedit" value="1"";s:9:"2048:2637";a:2:{s:4:"test";a:2:{s:15:"4:2645:canedit:";s:0:"";s:6:"2:2650";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:2659";s:8:" checked";}}s:6:"2:2838";s:174:"></td>
	</tr>
	<tr  >
		<th><label for="canadd">Право на создание:</label></th>
		<td ><input class="input" type="checkbox" name="canadd" id="canadd" value="1"";s:9:"2048:2842";a:2:{s:4:"test";a:2:{s:14:"4:2849:canadd:";s:0:"";s:6:"2:2854";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:2863";s:8:" checked";}}s:6:"2:3051";s:183:"></td>
	</tr>
	<tr  >
		<th><label for="cancopy">Право на копирование:</label></th>
		<td ><input class="input" type="checkbox" name="cancopy" id="cancopy" value="1"";s:9:"2048:3055";a:2:{s:4:"test";a:2:{s:15:"4:3063:cancopy:";s:0:"";s:6:"2:3068";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:3077";s:8:" checked";}}s:6:"2:3257";s:175:"></td>
	</tr>
	<tr  >
		<th><label for="canmove">Право на перенос:</label></th>
		<td ><input class="input" type="checkbox" name="canmove" id="canmove" value="1"";s:9:"2048:3261";a:2:{s:4:"test";a:2:{s:15:"4:3269:canmove:";s:0:"";s:6:"2:3274";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:3283";s:8:" checked";}}s:6:"2:3474";s:186:"></td>
	</tr>
	<tr  >
		<th><label for="canhide">Право на скрытие/показ:</label></th>
		<td ><input class="input" type="checkbox" name="canhide" id="canhide" value="1"";s:9:"2048:3478";a:2:{s:4:"test";a:2:{s:15:"4:3486:canhide:";s:0:"";s:6:"2:3491";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:3500";s:8:" checked";}}s:6:"2:3523";s:18:"></td>
	</tr>



	";s:9:"2048:3527";a:2:{s:4:"test";a:2:{s:21:"4:3541:num_datatypes:";s:0:"";s:6:"2:3545";s:3:" >0";}s:4:"true";a:3:{s:6:"2:3549";s:3:"
		";s:9:"2048:3553";a:2:{s:4:"test";a:2:{s:15:"4:3561:nfields:";s:0:"";s:6:"2:3566";s:4:" > 0";}s:4:"true";a:3:{s:6:"2:4226";s:659:"

		<tr >
			<td colspan=2 >
				&nbsp;
			</td>
		</tr>
		<tr >
			<td colspan=2 bgcolor="#EEEEEE">
				<p></p>
				<table cellspacing=0 cellpadding=3 border=0 width=90%>

					<tr >
						<td width=1%><b>Поля:</b></td>
						<td width=10%>имя</td>
						<td width=10%>ключ</td>
						<td width=15%>тип данных</td>
						<td width=10%>по умолчанию</td>
						<td width=20%>служебная информация</td>
						<td width=10%>аттрибуты</td>
						<td width=1%>сорт.</td>
						<td width=1%>неред.</td>
						<td width=1%>отобр.</td>
						<td width=10% >&nbsp;</td>
					</tr>

					
			
				";s:15:"16:4239:nfield:";a:49:{s:6:"2:4311";s:72:"
				<tr  >

					<td  align="left"  valign=center nowrap><b>Поле N ";s:9:"4:4313:i:";s:0:"";s:6:"2:4405";s:91:":&nbsp;</b></td>
					<td><input style="width:100%" class="input" type="text" name="nfieldn";s:9:"4:4407:i:";s:0:"";s:6:"2:4425";s:17:"" size=20 value="";s:8:"512:4430";a:3:{s:6:"2:4447";s:17:"htmlspecialchars(";s:15:"4:4455:nfieldn:";s:0:"";s:6:"2:4457";s:1:")";}s:6:"2:4552";s:89:""></td>

					<td>
					<input style="width:100%" class="input" type="text" name="nfieldk";s:9:"4:4554:i:";s:0:"";s:6:"2:4572";s:17:"" size=20 value="";s:8:"512:4577";a:3:{s:6:"2:4594";s:17:"htmlspecialchars(";s:15:"4:4602:nfieldk:";s:0:"";s:6:"2:4604";s:1:")";}s:6:"2:4657";s:47:"">

					<input type="hidden" name="old_name_f[";s:8:"512:4662";a:3:{s:6:"2:4679";s:17:"htmlspecialchars(";s:15:"4:4687:nfieldk:";s:0:"";s:6:"2:4689";s:1:")";}s:6:"2:4705";s:10:"]" value="";s:8:"512:4710";a:3:{s:6:"2:4727";s:17:"htmlspecialchars(";s:15:"4:4735:nfieldk:";s:0:"";s:6:"2:4737";s:1:")";}s:6:"2:4790";s:47:"">

					<input type="hidden" name="old_nfieldk";s:9:"4:4792:i:";s:0:"";s:6:"2:4802";s:9:"" value="";s:8:"512:4807";a:3:{s:6:"2:4824";s:17:"htmlspecialchars(";s:15:"4:4832:nfieldk:";s:0:"";s:6:"2:4834";s:1:")";}s:6:"2:4917";s:77:"">
					</td>

					<td><select style="width:100%" class="input" name="nfield";s:9:"4:4919:i:";s:0:"";s:6:"2:4929";s:9:"">
						";s:12:"16:4939:row:";a:9:{s:6:"2:4962";s:23:"
							<option value="";s:8:"512:4967";a:3:{s:6:"2:4984";s:17:"htmlspecialchars(";s:16:"4:4993:row[key]:";s:0:"";s:6:"2:4995";s:1:")";}s:6:"2:5003";s:2:"" ";s:16:"4:5012:selected:";s:0:"";s:6:"2:5023";s:10:">
								";s:8:"512:5028";a:3:{s:6:"2:5039";s:11:"strip_tags(";s:17:"4:5049:row[name]:";s:0:"";s:6:"2:5051";s:1:")";}s:6:"2:5059";s:2:" (";s:8:"512:5064";a:3:{s:6:"2:5081";s:17:"htmlspecialchars(";s:16:"4:5090:row[key]:";s:0:"";s:6:"2:5092";s:1:")";}s:6:"2:5123";s:25:")
							</option>
						";}s:6:"2:5233";s:103:"
						</select>
					</td>

					<td><input style="width:100%" class="input" type="text" name="nfieldd";s:9:"4:5235:i:";s:0:"";s:6:"2:5253";s:17:"" size=35 value="";s:8:"512:5258";a:3:{s:6:"2:5275";s:17:"htmlspecialchars(";s:15:"4:5283:nfieldd:";s:0:"";s:6:"2:5285";s:1:")";}s:6:"2:5374";s:83:""></td>

					<td><input style="width:100%" class="input" type="text" name="nfieldc";s:9:"4:5376:i:";s:0:"";s:6:"2:5394";s:17:"" size=35 value="";s:8:"512:5399";a:3:{s:6:"2:5416";s:17:"htmlspecialchars(";s:15:"4:5424:nfieldc:";s:0:"";s:6:"2:5426";s:1:")";}s:6:"2:5515";s:83:""></td>

					<td><input style="width:100%" class="input" type="text" name="nfielda";s:9:"4:5517:i:";s:0:"";s:6:"2:5536";s:18:"" size=35 	value="";s:8:"512:5541";a:3:{s:6:"2:5558";s:17:"htmlspecialchars(";s:15:"4:5566:nfielda:";s:0:"";s:6:"2:5568";s:1:")";}s:6:"2:5675";s:101:""></td>

					<td align="center"><input style="width:30px" class="input" type="text" name="nfieldsort";s:9:"4:5677:i:";s:0:"";s:6:"2:5696";s:18:"" size="3" value="";s:8:"512:5701";a:2:{s:9:"4:5703:i:";s:0:"";s:6:"2:5707";s:3:"*10";}s:6:"2:5767";s:54:""></td>

					<td><input type="checkbox" name="nfieldr";s:9:"4:5769:i:";s:0:"";s:6:"2:5795";s:25:"" class="input" value="1"";s:9:"2048:5799";a:2:{s:4:"test";a:2:{s:15:"4:5807:nfieldr:";s:0:"";s:6:"2:5812";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:5824";s:11:"    checked";}}s:6:"2:5881";s:52:"></td>
					<td><input type="checkbox" name="nfields";s:9:"4:5883:i:";s:0:"";s:6:"2:5909";s:25:"" class="input" value="1"";s:9:"2048:5913";a:2:{s:4:"test";a:2:{s:15:"4:5921:nfields:";s:0:"";s:6:"2:5926";s:4:" > 0";}s:4:"true";a:1:{s:6:"2:5936";s:9:"  checked";}}s:6:"2:6067";s:126:"></td>
					<td><input class="input"  type="button" value="убрать" onClick="javascript:document.form1.removefield.value=";s:9:"4:6069:i:";s:0:"";s:6:"2:6130";s:60:";document.form1.submit();return false;"></td>
				</tr>
				";}s:6:"2:6172";s:35:"


				</table>
			</td>
		</tr>
		";}}s:6:"2:6179";s:2:"
	";}}s:6:"2:6351";s:167:"


	<!--tr bgcolor="#EEEEEE">
		<td align="left" colspan=2><input style="width: 150px; height: 30px; font-weight: bold;" class="input" type="submit" name="add" value="";s:9:"2048:6355";a:2:{s:4:"test";a:2:{s:10:"4:6358:id:";s:0:"";s:6:"2:6361";s:2:">0";}s:4:"true";a:1:{s:6:"2:6380";s:18:"Сохранить";}}s:6:"2:6386";s:1:" ";s:9:"2048:6390";a:2:{s:4:"test";a:2:{s:10:"4:6393:id:";s:0:"";s:6:"2:6398";s:4:" < 1";}s:4:"true";a:1:{s:6:"2:6415";s:16:"Добавить";}}s:6:"2:6601";s:181:"">&nbsp;&nbsp;

		<INPUT name="Submit2" type="button" class="input" style="width: 100px; height: 30px;" value="Отмена" onclick="javascript:location.href='s_bltempl.php?parent=";s:14:"4:6608:parent:";s:0:"";s:6:"2:7124";s:515:"';return false;">&nbsp;&nbsp;
		<INPUT name="Submit3" type="button" class="input" style="width: 100px; height: 30px;" value="Добавить поле" onclick="document.form1.nfields.value++;document.form1.submit();return false;">&nbsp;&nbsp;
		</td>
	</tr//-->



	</table>

<p></p>
                                <a name="bottom_page"></a>
								<table align="center" style="width:300px">
									<tr>
									<td>
                                	<div class="save" ><input type="submit"  name="add" value="";s:9:"2048:7128";a:2:{s:4:"test";a:2:{s:10:"4:7131:id:";s:0:"";s:6:"2:7134";s:2:">0";}s:4:"true";a:1:{s:6:"2:7153";s:18:"Сохранить";}}s:6:"2:7159";s:1:" ";s:9:"2048:7163";a:2:{s:4:"test";a:2:{s:10:"4:7166:id:";s:0:"";s:6:"2:7171";s:4:" < 1";}s:4:"true";a:1:{s:6:"2:7188";s:16:"Добавить";}}s:6:"2:7621";s:428:"" /></div>
									</td>

									<td>
                                	<div class="save" ><input type="button"  value="Применить" onClick="document.form1.add2.value='1';  document.form1.submit(); return false;" /></div>
									</td>

									<td>
                                	<div class="cancel"><input name="Submit2" type="button" value="Отмена" onclick="javascript:location.href='s_bltempl.php?parent=";s:14:"4:7628:parent:";s:0:"";s:6:"2:8131";s:502:"';return false;"  /></div>
									</td>
									<td>
									<div class="save" ><input name="Submit3" type="button" value="Добавить поле" onclick="document.form1.nfields.value++;document.form1.submit();return false;" /></div>

									</td>
									</tr>
								</table>
                              	</div>

	</form>

            			</div>
            		</td>
                    <td class="block" style="width:10%">
            		</td>
                </tr>
            </table>

";}}