ETSa:2:{s:7:"0reduce";i:2;s:4:"main";a:24:{s:5:"2:974";s:948:"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>

<HEAD>
<TITLE>Система администрирования сайта - SoftMajor - 1</TITLE>
<META http-equiv="Content-Type" content="text/html; charset=utf-8">
<LINK href="styles/main.css" rel="stylesheet" type="text/css">
<LINK href="styles/styles.css" rel="stylesheet" type="text/css">

<script>

	function check_iframe()		{

		var arr = document.getElementsByTagName('iframe');
		for (i = 0; i < arr.length; i++)		{
			var id = arr[i].id;
			if (id.substr(0, 7) == 'ifrdata')	{
				var id2 = id + '_hid';				
				document.getElementById(id2).value = document.getElementById(id).contentWindow.GetContents();
				//alert (document.getElementById(id2).value);
			}
		}
		//alert (arr.length);

		//alert ('d');
		return true;
	}
</script>

<script language="javascript" type="text/javascript" src="js/popcalendar.js"></script>	
<script language="javascript">
<!--




";s:6:"2:1490";s:570:"n//s---------------------------------------n//sЦентральнаяsфункцияsопределения.n//s---------------------------------------nfunctions$(id)n{nsssreturnsdocument.getElementById(id);n}nnnfunctionsback_b()n{nslocation.href='item_edit.php?blockparent='+$('blockparent').value+'&template='+$('template').value+'&blockid='+$('blockid').value+'&parent='+$('parent').valuen}n//s=sdocument.body.offsetHeight+100n
//-->
</script>
</HEAD>

<body  onload="parent.document.getElementById('itemframe";s:16:"4:1499:template:";s:0:"";s:6:"2:2063";s:563:"').height = $('divtable').offsetHeight+150" bgcolor="#e4e4e4" style="background: #fff url(../img/e.gif); width:100%; min-width:300px;">



<table class="center" cellpadding="0" cellspacing="0" border="0">
	<tr>
    	<td class="cont"  style="padding:5px">
			<div id="div_cont" style="padding:0px">

<table class="in_cont" cellpadding="0" cellspacing="0" border="0" style="width:100%; padding-top:0px; margin-top:0px"  >
<tr>
<td align="center" style="padding:0px" valign="top">

<div class="with_page"  style="padding:0px" >



<form action="item_edit.php?action=";s:14:"4:2070:action:";s:0:"";s:6:"2:2084";s:13:"&blockparent=";s:19:"4:2096:blockparent:";s:0:"";s:6:"2:2107";s:10:"&template=";s:16:"4:2116:template:";s:0:"";s:6:"2:2125";s:8:"&parent=";s:14:"4:2132:parent:";s:0:"";s:6:"2:2142";s:9:"&blockid=";s:11:"4:2146:bid:";s:0:"";s:6:"2:2347";s:200:"" method="POST"  enctype="multipart/form-data" name="form1"  onSubmit="return check_iframe();">
<input type="hidden" name="blockid" id="blockid">
<input type="hidden" name="parent" id="parent" value="";s:14:"4:2354:parent:";s:0:"";s:6:"2:2416";s:61:"">
<input type="hidden" name="template" id="template" value="";s:16:"4:2425:template:";s:0:"";s:6:"2:2493";s:67:"">
<input type="hidden" name="blockparent" id="blockparent" value="";s:19:"4:2505:blockparent:";s:0:"";s:6:"2:2571";s:65:"">

<table cellpadding="0" cellspacing="0" border="0" >

<tr><th>";s:9:"2048:2575";a:2:{s:4:"test";a:2:{s:6:"2:2576";s:1:"!";s:19:"4:2588:blockparent:";s:0:"";}s:4:"true";a:1:{s:6:"2:2680";s:90:"Для создания вложений необходимо сохранить блок ";}}s:6:"2:2696";s:11:"</td></tr>
";s:9:"2048:2700";a:2:{s:4:"test";a:1:{s:19:"4:2712:blockparent:";s:0:"";}s:4:"true";a:3:{s:6:"2:2715";s:1:"
";s:15:"16:2728:values:";a:10:{s:6:"2:2756";s:28:"
   <tr><th width="100px">
	";s:12:"4:2761:name:";s:0:"";s:9:"2048:2766";a:2:{s:4:"test";a:1:{s:12:"16:2779.1://";a:1:{s:18:"4:2779:superadmin:";s:0:"";}}s:4:"true";a:3:{s:6:"2:2805";s:24:"<br><font color="green">";s:11:"4:2809:key:";s:0:"";s:6:"2:2817";s:7:"</font>";}}s:6:"2:2872";s:50:"</th>
	<th style="text-align:left !important;" >
	";s:13:"4:2878:value:";s:0:"";s:6:"2:2920";s:41:"<input type="hidden" name="dat[]" value="";s:11:"4:2924:key:";s:0:"";s:6:"2:2969";s:44:""><input type="hidden" name="dkey[]" value="";s:16:"4:2978:datatkey:";s:0:"";s:6:"2:2992";s:13:""></th></tr>
";}s:6:"2:3002";s:3:"


";}}s:6:"2:3278";s:271:"
</TABLE>
<p align="left"><input type="submit" value="Сохранить">&nbsp;<input type="button" onclick="back_b();" value="<= Вернуться к списку"></p>
</form>

</div>
</td>
<td>&nbsp;</td>
</tr>
</table>
</div>
</td>
</tr>
</table>


</BODY>
</HTML>
";}}