<?php
// AUTOGENERATED
// PHP 5.2 Support (recommended php version)
$prname = "smcontents";

$config = array();
$config['dbhost'] = 'localhost';

$config['dbname'] = 'rushydro15';
$config['dbuser'] = 'rushydro15';
$config['dbpass'] = 'zW4Nqacn6S';
//настройка типа кодировки соединения с MYSQL
$config['mysql_set_names'] = 'utf8';


$config['site_name'] = 'РусГидро – 15 лет!';
